import Header from '@components/Header';
import NavBar from '@components/NavBar';
import QuickLinks from '@components/QuickLinks';
import { Box, Flex } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { useEffect } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Flex width='100vw' height='100vh' maxHeight='100vh'>
      <NavBar />
      <Flex direction='column' width='100%'>
        <Flex>
          <Header />
        </Flex>
        {children}
      </Flex>
    </Flex>
  );
}
