import { Box, Flex } from "@radix-ui/themes";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Flex width="100vw" height="95vh" justify="center" align="center">
      <Flex direction="column" gap="8" align="center">
        <img src="/logo-text.svg" alt="logo" style={{ width: 256 }} />
        {/* TODO: Replace img with svg sprites*/}
        {children}
      </Flex>
    </Flex>
  );
}
